apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: spring-cloud
  annotations:
    kompose.cmd: kompose -f docker-compose-springcloud-datacenter.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - image: springcloud/gateway:latest
        imagePullPolicy: Never
        name: springcloud-gateway
        ports:
        - containerPort: 9080
        resources: {}
      hostname: gateway
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  namespace: spring-cloud
  annotations:
    kompose.cmd: kompose -f docker-compose-springcloud-datacenter.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
  - name: "gateway"
    port: 9080
    targetPort: 9080
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
