apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: spring-cloud
  annotations:
    kompose.cmd: kompose -f docker-compose-springcloud-datacenter.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: turbine
  name: turbine
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: turbine
    spec:
      containers:
      - image: springcloud/turbine:latest
        imagePullPolicy: Never
        name: springcloud-turbine
        resources: {}
      hostname: turbine
      restartPolicy: Always
status: {}
